#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'IRCamera','console_scripts','ir_pub'
__requires__ = 'IRCamera'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('IRCamera', 'console_scripts', 'ir_pub')()
    )
